# Generated by Django 5.0.6 on 2024-06-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='UnitSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit_type', models.CharField(choices=[('COMMON_AREA', 'Common Area'), ('VACANT', 'Vacant'), ('LEASED', 'Leased')], default='COMMON_AREA', max_length=32)),
                ('area', models.FloatField()),
                ('property_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.propertyspace')),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=128)),
                ('meter_provider_name', models.CharField(max_length=128)),
                ('meter_source', models.CharField(max_length=128)),
                ('measurement_reading', models.FloatField()),
                ('measurement_unit', models.CharField(choices=[('kWh', 'kWh'), ('therms', 'Therms')], default='kWh', max_length=32)),
                ('measurement_start_date', models.DateTimeField()),
                ('measurement_end_date', models.DateTimeField()),
                ('unit_space', models.ManyToManyField(to='api.unitspace')),
            ],
        ),
    ]
